# @package training
frames_per_batch: 2048
total_frames: 500000
sub_batch_size: 64
num_epochs: 10
clip_epsilon: 0.2
gamma: 0.99
lmbda: 0.95
entropy_eps: 0.01
max_steps: 10000
critic_coef: 0.5
average_gae: true
normalize_advantage: true
eval_freq: 6144
eval_rollout_freq: 10
lr: 3e-4
max_grad_norm: 0.5
split_trajs: false
loss_critic_type: "smooth_l1"
action_masking: true
